# -----------------
# Stage 1: Builder
# -----------------
FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip wheel setuptools

COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=100 \
    --target=/install -r requirements.txt

COPY . .

# -----------------
# Stage 2: Final Image
# -----------------
FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /install /usr/local/lib/python3.12/site-packages
COPY --from=builder /app /app

EXPOSE 8000

# Dev mode: use Django's runserver
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
